apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 81;
        location / {
          return 200 "OK, Default Path";
        }
        location /hello {
          return 200 "Hello World";
        }
        location /Brazil {
          return 200 "Bad at football";
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 12.5%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-volume
        configMap:
          name: nginx-config
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports: 
        - containerPort: 81
        volumeMounts:
        - name: nginx-volume
          mountPath: /etc/nginx/
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer 
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 81
    targetPort: 81